### ISSUE TITLE
Tutorial on setting up android emulator

### ISSUE THREAD

**Issue by rafale77** [jghaanstra/com.robot.xiaomi-mi#2]
Been pulling my hairs over how to make the Mi Home app work on Bluestacks. Setting up the android network environment is not trivial since by default it runs through a NAT straight through your computer to the net and will not be part of your local network.
So far on Mac it has not been possible.
On Windows 10 the only emulator I found to work Leapdroid. It uses Vbox 5 and enables network bridging. Bluestacks on Mac Sierra and Win10 run on Vbox4 and do not allow you to change any network parameters due to incompatibility with Vbox4. If you use Win7 or Win8.1 Bluestack can work but you will need some additional tools to setup the network and enable a bridge into your local network. Hope it helps someone. I am not quite sure how the author made it work on a mac.

**Comment by jghaanstra** [comment]
I had no issues on Windows 10. Just installed BlueStacks and it worked out of the box. Then installed Mi Home from the app store and everything was fine. As mentioned in the tutorial I also did not came up with the tutorial but copied it from here: https://www.domoticz.com/forum/viewtopic.php?p=113345#p113345

I have no further knowledge on BlueStacks but perhaps Sevift (original author) can help you with this. Since this is a repository for an appto control the Mi Robot intended for the domotica controller Homey by Athom I'm closing this issue.
