### ISSUE TITLE
Wireshark don't capture the frame of bluestacks

### ISSUE THREAD

**Issue by anktababa** [jghaanstra/com.robot.xiaomi-mi#5]
Hello,
First of all, Thank you for your work and for the research !
I am running on Windows 10, I use Bluestack with the Mi App inside it and i am able to start/stop the robot. When capturing traffic using wireshark, this one is capturing all of the traffic of my VM but it seems that it doesn't capture anything from Bluestacks, so i was wondering if there is something specific to do to make it work.
The only thing that could be specific in my case, is the fact that i am running my Windows 10 inside a VM on my ESXI server, so it could be the reason but if it is the case i don't know why.
Did you run it directly on your system or are you using a VM to this test ?

Thank you !

**Comment by jghaanstra** [comment]
I ran BluesStacks directly on my Windows 10 install. I can imaging running it inside a VM can somehow cause issues. But as mentioned in the tutorial I did not came up with the tutorial myself but copied it from here: https://www.domoticz.com/forum/viewtopic.php?p=113345#p113345

I have no further knowledge on BlueStacks but perhaps Sevift (original author) can help you with this. Since this is a repository for an app to control the Mi Robot intended for the domotica controller Homey by Athom I'm closing this issue.
